### ISSUE TITLE
No such module 'Quick'

### ISSUE THREAD

**Issue by sabymike** [Quick/Quick#195]
I can't seem to get the Quick and Nimble projects to build as dependencies and show up in my project. I keep getting "No such module" when I try to import either module Quick or Nimble into my Swift test file. When I add these projects to my workspace, Quick.framework is marked red and missing even when I build the application for testing. When I change my scheme to the Quick-iOS scheme, the Quick.framework turns black and is "present" but disappears again when I change to my app scheme.

Are the installation instructions up to date for XCode 6? I even created a clean test bundle to make sure I wasn't saving any old configuration settings. I'm not sure what else to do to troubleshoot this issue.

**Comment by fergalrooney** [comment]
@sabymike When modifying the configurations in the Nimble and Quick projects, how did you persist the change? I am currently using git submodules to test out this framework. If another developer wants to use my branch, the submodules will be downloaded without these changes.

**Comment by sabymike** [comment]
@fergalrooney I not sure how you would make this persist using submodules for other developers. I have since stopped using Quick in my project so I haven't kept up with maintaining these settings.

**Comment by fergalrooney** [comment]
@sabymike Thanks for the reply. It sounds like Cocoapods is the way to go for having custom build configuration names as it automatically configures these for you when the Pods project is generated. Will wait for its next release as its currently in beta.

**Comment by priteshshah1983** [comment]
@fergalrooney Were you able to try this with CocoaPods? I am using custom build configurations and tried with ````0.36.3```` and I still get the same error.

**Comment by fergalrooney** [comment]
@priteshshah1983 Yes I was able to integrate successfully using cocoapods v0.36. I am using Quick v0.3.1 and Nimble v0.4.2. I needed to specify use_frameworks! in my Podfile and everything worked seamlessly. Are you getting any warnings / errors outputted from pod install?

**Comment by priteshshah1983** [comment]
Thanks @fergalrooney! I just found out that my custom build configuration was overwriting the ````FRAMEWORK_SEARCH_PATHS```` set by CocoaPods. I fixed that and everything is great now.

**Comment by onmyway133** [comment]
For me, it is because I haven't told Carthage to build. This makes it

```
carthage build --platform iOS,Mac
```

**Comment by alexvbush** [comment]
I had the same issue. Resolved it with adjusting test target build settings to not always include swift modules

The clue was the following warning from cocoapods after running `pod install`:

```
[!] The `StashTests [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-StashTests/Pods-StashTests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `StashTests [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-StashTests/Pods-StashTests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Comment by alexvbush** [comment]
hm, actually, the issue is still there :) the funny thing is that it compiles and runs tests just fine. it simply complains about `import Quick`
![screenshot 2016-12-03 16 45 04](https://cloud.githubusercontent.com/assets/311077/20863194/e13ae134-b977-11e6-9880-7da540093244.png)

**Comment by jeffh** [comment]
@alexvbush, that Xcode quirk occurs every once in awhile for me. For whatever reason, cleans / recompiles sometimes resolves it 😅
